services:
  database:
    image: postgres:15-alpine
    container_name: bangers_db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-bangers_backend}"
      POSTGRES_USER: "${DB_USERNAME:-root}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
